fix: Properly get key from file when it contains more than just the key
aneoconsulting/ArmoniK.Api pull request #298
Opened 2023-06-13 13:28 UTC by dbrasseur-aneo

2023-06-13 13:33 UTC, aneojgurhem commented on packages/csharp/ArmoniK.Api.Client/ArmoniK.Api.Client.csproj
> +    <PackageVersion>3.8.2</PackageVersion>
c'est tous les paquets qui doivent changer et non pas que celui la. Normalement la pipeline te jette

2023-06-13 13:35 UTC, aneojgurhem commented
pourquoi tu ne pars pas de la 3.8.1 ?

2023-06-13 13:37 UTC, dbrasseur-aneo commented
> pourquoi tu ne pars pas de la 3.8.1 ?

J'étais parti de là... je comprend pas pk ça n'a pas pris en compte ?

2023-06-13 13:38 UTC, aneojgurhem commented
ton tag local et le remote ne sont pas le meme je dirais

2023-06-13 13:41 UTC, aneojgurhem commented
```
git checkout 3.8.1 && git rev-parse HEAD
```

2023-06-13 13:51 UTC, ddiakiteaneo approved these changes

2023-06-13 13:53 UTC, aneojgurhem requested changes

2023-06-13 13:53 UTC, aneojgurhem commented on packages/csharp/ArmoniK.Api.Common.Channel/ArmoniK.Api.Common.Channel.csproj
> -    <PackageVersion>3.8.0</PackageVersion>
Required

2023-06-13 14:31 UTC, landdragon commented
en fait on a l'impression que le problème viens du cast de AsymmetricKeyParameter vers AsymmetricCipherKeyPair

2023-06-13 14:47 UTC, landdragon commented
lors du ReadObject
```
  var pemReader = new PemReader(reader);
  var keyPair   = pemReader.ReadObject()
```
on passe par du code qui retourne un AsymmetricKeyParameter (par ce que notre private key commencer par `-----BEGIN PRIVATE KEY-----`)

2023-06-14 07:41 UTC, aneojgurhem commented on packages/csharp/ArmoniK.Api.Client/ArmoniK.Api.Client.csproj
> +    <PackageVersion>3.8.2</PackageVersion>
ainsi que ceux des autres langages ! @dbrasseur-aneo

2023-06-14 08:47 UTC, dbrasseur-aneo commented
> lors du ReadObject
> 
> ```
>   var pemReader = new PemReader(reader);
>   var keyPair   = pemReader.ReadObject()
> ```
> 
> on passe par du code qui retourne un AsymmetricKeyParameter (par ce que notre private key commencer par `-----BEGIN PRIVATE KEY-----`)

Quel algorithme de clé utilisez vous ? Ed25519 ?

2023-06-14 09:36 UTC, landdragon commented
on utilise du RSA

2023-06-14 09:53 UTC, landdragon commented
on est en RSA mais sous le format pkcs8 :
https://stackoverflow.com/questions/20065304/differences-between-begin-rsa-private-key-and-begin-private-key

2023-06-14 09:54 UTC, dbrasseur-aneo commented
> on utilise du RSA

Un fichier au format PEM RSA est censé commencer par "-----BEGIN RSA PRIVATE KEY-----"
pas "-----BEGIN PRIVATE KEY-----"

Parmi mes tests avec RSA, ECDSA et le ED25519, le seul format que j'ai vu qui commence par "-----BEGIN PRIVATE KEY-----" est le ED25519.

Je n'ai pas vraiment d'explication autre.
RSA et ECDSA renvoient bien un AsymmetricCipherKeyPair quand il passe dans la fonction
ED25519 renvoit un Ed25519PrivateKeyParameters qui est un AsymmetricKeyParameter

Si la clé est bien du ED25519 et non du RSA, alors c'est un cas particulier non prévu...

2023-06-14 09:57 UTC, dbrasseur-aneo commented
> on est en RSA mais sous le format pkcs8 : https://stackoverflow.com/questions/20065304/differences-between-begin-rsa-private-key-and-begin-private-key

Ok, je vous tiens au courant pour un fix

2023-06-16 08:38 UTC, lemaitre-aneo submitted a review, later dismissed

2023-06-16 08:38 UTC, lemaitre-aneo commented on packages/csharp/ArmoniK.Api.Client/Submitter/GrpcChannelFactory.cs
> -                          new AsymmetricKeyEntry(keyPair.Private),
I think you could avoid casting duplication with the following:

```c#
        var                     pemReader = new PemReader(reader);
        AsymmetricKeyParameter? key;

        do
        {
          key = pemReader.ReadObject() switch
                {
                  null                            => throw new CryptographicException("Key could not be retrieved from file"),
                  AsymmetricCipherKeyPair keyPair => keyPair.Private,
                  AsymmetricKeyParameter keyParam => keyParam,
                  _                               => null,
                };
        } while (key is null);

        store.SetKeyEntry("alias",
                          new AsymmetricKeyEntry(key),
                          new X509CertificateEntry[]
                          {
                            new(cert),
                          });
```

2023-06-16 09:40 UTC, lemaitre-aneo approved these changes

2023-06-16 10:25 UTC, merged