feat: add stats module in Python API
aneoconsulting/ArmoniK.Api pull request #474
Opened 2024-02-08 15:08 UTC by qdelamea-aneo

- feat: add module to compute statistics
- feat: improve stats module for Python API

2024-02-09 15:32 UTC, ngruelaneo requested changes
cette PR devrait etre coupé en deux. Celles qui implémente les nouvelles API et celle avec les stats. La première a de grande chance d'être mergé, la seconde devra probablement devenir sont propre projet.

2024-02-09 15:44 UTC, aneojgurhem commented
> cette PR devrait etre coupé en deux. Celles qui implémente les nouvelles API et celle avec les stats. La première a de grande chance d'être mergé, la seconde devra probablement devenir sont propre projet.

Pour le coup la premiere partie est deja dans une autre pr et mergée il me semble

2024-02-09 15:48 UTC, ngruelaneo requested changes

2024-02-09 15:48 UTC, ngruelaneo commented on packages/python/src/armonik/utils/stats.py
> +    def finalize(self, start: datetime, end: datetime):
si tu utilises le typing fait le jusqu'au bout et n'oublie pas le retour

2024-02-09 15:48 UTC, ngruelaneo commented on packages/python/src/armonik/utils/stats.py
> +        self.name = name
a quoi sert cet attribut? Il n'est utilisé nul part. Vu la suite du code, il ne sert à rien et tu devrais utiliser `__qualname__` pour obtenir l'information voulu. cf: https://peps.python.org/pep-3155/

2024-02-09 15:48 UTC, ngruelaneo commented on packages/python/src/armonik/utils/stats.py
> +        self.throughput = float(self.total) / (end - start).total_seconds()
depuis python 3 tu n'as plus besoin de transformer en float si ton chiffre est un entier (comme defini dans le type du dessus)

2024-02-09 15:48 UTC, ngruelaneo commented on packages/python/src/armonik/utils/stats.py
> +        super().__init__("total_elapsed_time")
inutile

2024-02-09 15:48 UTC, ngruelaneo commented on packages/python/src/armonik/utils/stats.py
> +        super().__init__("avg_throughput")
inutile

2024-02-09 15:48 UTC, ngruelaneo commented on packages/python/src/armonik/utils/stats.py
> +        super().__init__(f"{status_1}_to_{status_2}")
inutile tu ne t'en sers pas

2024-02-09 15:48 UTC, ngruelaneo commented on packages/python/src/armonik/utils/stats.py
> +        super().__init__(f"{status}_over_time")
inutile

2024-02-13 13:44 UTC, ngruelaneo commented on packages/python/pyproject.toml
> +    "numpy",
create another env in the pyproject (stat) similar to the dev one. We don't need to install numpy for armonik

2024-02-13 17:00 UTC, ngruelaneo commented on packages/python/src/armonik/stats/metrics/base.py
> +from ...common import Task
Attention à cet import qui ne sera plus valide lorsque tu sortiras ce fichier de l'api

2024-02-13 17:13 UTC, ngruelaneo commented on packages/python/src/armonik/stats/metrics/transitions.py
> +            timestamp_1 (str): The first timestamp.
mieux par contre pas sur que tu ais besoin de redefinir les types du coup dans la docstring (si on met la bonne extension cela est ok donc sort la de cet endroit)

2024-02-14 08:15 UTC, ngruelaneo commented on packages/python/src/armonik/stats/metrics/common.py
> +        self.throughput = float(self.total) / (end - start).total_seconds()
```suggestion
        self.throughput = self.total / (end - start).total_seconds()
```

2024-03-06 08:24 UTC, ngruelaneo approved these changes

2024-03-06 08:29 UTC, closed without merging

2024-03-06 08:29 UTC, ngruelaneo commented
outdated