Move python package related files to the Api/python folder
aneoconsulting/ArmoniK.Api pull request #53
Opened 2022-09-22 10:38 UTC by dbrasseur-aneo

2022-09-26 12:22 UTC, aneojgurhem requested changes

2022-09-26 12:22 UTC, aneojgurhem commented on .github/workflows/build.yml
> +      uses: actions/checkout@v2
ici tu peux lui dire de faire une copie complete du repo, regarde le job versionning

`fetch-depth: 0`

2022-09-26 12:22 UTC, aneojgurhem commented on .github/workflows/release.yml
> +    - name: Get history and tags for SCM versioning to work
idem

2022-09-26 12:22 UTC, aneojgurhem commented on Api/python/proto2python.sh
> +# sudo apt install python3-venv python3 python-is-python3 pip
heureusement que c'est un commentaire.

2022-09-26 13:56 UTC, dbrasseur-aneo commented on .github/workflows/build.yml
> +      uses: actions/checkout@v2
Done

2022-09-26 13:56 UTC, dbrasseur-aneo commented on Api/python/proto2python.sh
> +# sudo apt install python3-venv python3 python-is-python3 pip
Oui, pour le coup c'est la ligne que j'ai du utiliser sur wsl pour que ça marche de mon côté

2022-09-26 17:22 UTC, ngruelaneo commented on Api/python/README.md
> +# ArmoniK.Api Python package
Pour la doc je mettrais une partie sur la creation des packages (ce que tu as presque fait)
et une deuxième pour expliquer l'installation des paquets à partir de pypi

2022-09-26 17:22 UTC, ngruelaneo commented on Api/python/README.md
> +To generate the package from sources, run the proto2python.sh script.
met un exemple de comment s'en servir:

```bash
bash proto2python.sh ~/Venv/armonik_grpc
```

Préciser que cela ne fonctionnera que avec bash sous wsl ou un linux ubuntu

2022-09-26 17:22 UTC, ngruelaneo commented on Api/python/proto2python.sh
> +# sudo apt install python3-venv python3 python-is-python3 pip
il y a véritablement besoin d'installer python3?
pour pip ne serait ce pas python3-pip?

2022-09-26 17:22 UTC, ngruelaneo commented on Api/python/proto2python.sh
> +touch $ARMONIK_WORKER/__init__.py
ouh la la la boulette que j'avais fait :)

2022-09-27 13:39 UTC, dbrasseur-aneo commented on Api/python/proto2python.sh
> +# sudo apt install python3-venv python3 python-is-python3 pip
Apparemment mon WSL n'avait, de base, que python 2...

2022-09-27 13:39 UTC, dbrasseur-aneo commented on Api/python/README.md
> +To generate the package from sources, run the proto2python.sh script.
Done

2022-09-27 13:39 UTC, dbrasseur-aneo commented on Api/python/README.md
> +# ArmoniK.Api Python package
Done

2022-09-27 14:41 UTC, merged