fix: Python API event client wait_for_result_availability method
aneoconsulting/ArmoniK.Api pull request #530
Opened 2024-07-17 10:19 UTC by qdelamea-aneo

- fix: Python API event client wait_for_result_availability method
- fix: Python event client

2024-07-17 10:19 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/aneoconsulting/ArmoniK.Api?pullRequest=530) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/aneoconsulting/ArmoniK.Api?pullRequest=530) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: qdelamea-aneo<br/>:x: salma-aneo<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/aneoconsulting/ArmoniK.Api?pullRequest=530) it.</sub>

2024-07-17 12:49 UTC, dbrasseur-aneo requested changes

2024-07-17 12:49 UTC, dbrasseur-aneo commented on packages/python/src/armonik/client/events.py
> +            if task_filter
```suggestion
            if task_filter is not None
```
Filters to not implement "truthyness" as they can't be converted to booleans. Other instances of this are present in other parts of the file

2024-07-17 12:49 UTC, dbrasseur-aneo commented on packages/python/src/armonik/client/events.py
> +                    break
This does not do what the docstring describes.
When an handler return True, it stops processing other handlers, but it doesn't stop listening as the "break" does not break the message loop.
you could use :  
```suggestion
            if all(not event_handler(
                session_id,
                EventTypes.from_string(event_type),
                self._events_obj_mapping[event_type].from_raw_event(
                    getattr(message, event_type)
                ),
            ) for event_handler in event_handlers):
                break
```

2024-07-17 12:49 UTC, dbrasseur-aneo commented on packages/python/src/armonik/client/events.py
> +    def wait_for_result_availability(self, result_ids: List[str], session_id: str) -> None:
I would keep the old one too with a
```suggestion
    def wait_for_result_availability(self, result_ids: Union[str, List[str]], session_id: str) -> None:
```
And wrap the singular one in a list
for Api compatibility

2024-07-17 12:49 UTC, dbrasseur-aneo commented on packages/python/src/armonik/client/events.py
> +        results_not_found = deepcopy(result_ids)
A simple copy should be sufficient, as a string is immutable in Python

2024-07-17 12:49 UTC, dbrasseur-aneo commented on packages/python/src/armonik/client/events.py
> +        results_filter = ResultFieldFilter.RESULT_ID == result_ids[0]
Needs a check for empty list

2024-08-23 07:11 UTC, aneojgurhem approved these changes

2024-08-23 07:28 UTC, merged