feat: create results endpoints and messages
aneoconsulting/ArmoniK.Api pull request #62
Opened 2022-09-27 10:13 UTC by esoubiran-aneo

2022-09-27 10:15 UTC, aneojgurhem requested changes

2022-09-27 10:15 UTC, aneojgurhem commented on Protos/V1/results_common.proto
> +  string id = 1; /** The result ID. */
Je pense pas qu'il faille exposer l'id ici. C'est un détail d'implémentation interne

2022-09-27 16:01 UTC, esoubiran-aneo commented on Protos/V1/results_common.proto
> +  string id = 1; /** The result ID. */
done

2022-10-03 12:12 UTC, aneojgurhem approved these changes

2022-10-03 12:12 UTC, merged