API to generate events on tasks and results updates in order to visualize them as a graph
aneoconsulting/ArmoniK.Api pull request #81
Opened 2022-11-10 17:20 UTC by aneojgurhem

This PR adds an new API for a service called Events. This service can be used to receive events related to the update of tasks and results whithin a session. The endpoint can be called to listen to the modifications of multiple sessions if needed. These events can be used to form the graph of data dependencies between the tasks of a session.

As for now, all the events of a session will be sent whithout filtering. It is possible that the API will evolve to a more refined way to filter the events to be received.

Note : https://hackmd.io/@7eo8p7wrSFKWO6IX2OzTpA/rJhRMhYro

2022-11-14 15:50 UTC, esoubiran-aneo commented
Can you provide the link to the hackmd @aneojgurhem to know intents and purposes?

2022-11-14 15:52 UTC, esoubiran-aneo commented on Protos/V1/graphs_common.proto
> +   * Represents a new result to add to the graph
```suggestion
   * Represents a new result to add to the graph.
```

2022-11-14 15:52 UTC, esoubiran-aneo commented on Protos/V1/graphs_common.proto
> +   * Represents a new task to add to the graph
```suggestion
   * Represents a new task to add to the graph.
```

2022-11-14 15:52 UTC, esoubiran-aneo commented on Protos/V1/graphs_common.proto
> +   * Represents an update to the owner task id of a result
```suggestion
   * Represents an update to the owner task id of a result.
```

2022-11-14 15:52 UTC, esoubiran-aneo commented on Protos/V1/graphs_common.proto
> +   * Represents an update to the status of a result
```suggestion
   * Represents an update to the status of a result.
```

2022-11-14 15:52 UTC, esoubiran-aneo commented on Protos/V1/graphs_common.proto
> +   * Represents an update to the status of a task
```suggestion
   * Represents an update to the status of a task.
```

2022-11-14 16:00 UTC, esoubiran-aneo requested changes

2022-11-14 16:00 UTC, esoubiran-aneo commented on Protos/V1/graphs_common.proto
> +    string payload_id = 41; /** The payload id. **/
C'est vraiment utile de savoir ça pour l'affichage du graph ?

2022-11-14 16:00 UTC, esoubiran-aneo commented on Protos/V1/graphs_common.proto
> +    string origin_task_id = 42; /** The task id before retry. **/
Tu peux ajouter plus de détails sur la gestion des retry ?

2022-11-15 09:43 UTC, aneojgurhem commented on Protos/V1/graphs_service.proto
> +  rpc GetResultIds(GraphSubscriptionRequest) returns (stream GraphContentResponse);
Je pense que c'est un copier/coller malheureux. Je change ça^^

2022-11-16 09:31 UTC, aneojgurhem commented on Protos/V1/graphs_common.proto
> +    string payload_id = 41; /** The payload id. **/
Si tu veux aussi afficher les données en entrées, oui. Dans le cas actuel, on peut s'en passer.

2023-01-09 06:40 UTC, aneojgurhem commented on Protos/V1/graphs_common.proto
> +    string origin_task_id = 42; /** The task id before retry. **/
Je pense que ce n'est pas ici le plus pertinent pour mettre des infos sur les retries. Je vais essayer d'écrire de la doc sur le sujet et l'intégrer dans core. Il y a un début ici : https://github.com/aneoconsulting/ArmoniK.Core/blob/main/Documentation/articles/tasks.md

2023-01-09 06:52 UTC, aneojgurhem commented on Protos/V1/graphs_service.proto
> + * Graph visualization related methods within a service.
j'hésite à l'appeler Events !

2023-01-09 07:11 UTC, Barbapapazes commented on Protos/V1/graphs_service.proto
> + * Graph visualization related methods within a service.
Yes ça peut avoir beaucoup de sens si la finalité de l'api c'est ça et que la création de graph n'est que manière d'utiliser ces events et de les Lier entre eux

2023-01-09 07:20 UTC, aneojgurhem commented on Protos/V1/graphs_service.proto
> + * Graph visualization related methods within a service.
On est clairement dans le cas où on a des events et qu'on les interprète comme étant les modifications d'un graphe. A aucun moment le service te renvoie un graphe dans un format de graphe.

2023-01-09 09:26 UTC, esoubiran-aneo commented on Protos/V1/events_common.proto
> +message EventContentResponse {
```suggestion
message EventSubscriptionResponse {
```

2023-01-09 09:26 UTC, esoubiran-aneo commented on Protos/V1/events_service.proto
> +  rpc GetEvents(EventSubscriptionRequest) returns (stream EventContentResponse);
```suggestion
  rpc GetEvents(EventSubscriptionRequest) returns (stream EventSubscriptionResponse);
```

2023-01-09 09:26 UTC, esoubiran-aneo commented on Protos/V1/events_common.proto
> +message EventContentResponse {
Harmonisation du nom de la requête et de la response

2023-01-09 09:26 UTC, esoubiran-aneo commented on Protos/V1/events_common.proto
> +    string previous = 31; /** The previous owner. **/
Est-ce que c'est un `id` ? Parce que ligne 66, c'est un `id` pour owner.

2023-01-09 09:26 UTC, esoubiran-aneo commented on Protos/V1/events_common.proto
> +  oneof update {
Est-ce que ça ne serait pas intéressant de mettre un flag avec une énumération pour savoir le type de l'event envoyer par le serveur ?

2023-01-09 09:27 UTC, esoubiran-aneo commented on Protos/V1/graphs_common.proto
> +    string origin_task_id = 42; /** The task id before retry. **/
Yes, c'est pas mal aussi directement dans la documentation.

2023-01-09 09:30 UTC, aneojgurhem commented on Protos/V1/events_common.proto
> +    string previous = 31; /** The previous owner. **/
oui c'est aussi un id

2023-01-09 09:31 UTC, aneojgurhem commented on Protos/V1/events_common.proto
> +  oneof update {
ce flag est généré par gRPC. En c#, c'est le cas

2023-01-09 09:36 UTC, esoubiran-aneo commented on Protos/V1/events_common.proto
> +  oneof update {
Ok Ok !

2023-01-09 09:36 UTC, esoubiran-aneo commented on Protos/V1/events_common.proto
> +    string previous = 31; /** The previous owner. **/
du coup, ça peut être bien d'harmoniser les noms avec `previous_owner_id` et avec `current_owner_id`

2023-01-09 09:39 UTC, esoubiran-aneo requested changes

2023-01-09 09:39 UTC, esoubiran-aneo commented on Protos/V1/events_common.proto
> +    repeated string expected_output_keys = 44; /** The task id. **/
fix docs

2023-01-09 09:39 UTC, esoubiran-aneo commented on Protos/V1/events_common.proto
> +    repeated string data_dependencies = 45; /** The task id. **/
fix docs

2023-01-09 09:39 UTC, esoubiran-aneo commented on Protos/V1/events_common.proto
> +    string task_id = 10; /** The result id. **/
fix docs

2023-01-09 09:44 UTC, esoubiran-aneo approved these changes

2023-01-09 09:45 UTC, merged